//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XperienceAdapter.Models.ReusableFieldSchemas.SEOFields.SEOFields
{
    /// <summary>
    /// Defines a contract for content types with the <see cref="ISEOFields"/> reusable schema assigned.
    /// </summary>
    public interface ISEOFields
    {
        /// <summary>
        /// Code name of the reusable field schema.
        /// </summary>
        public const string REUSABLE_FIELD_SCHEMA_NAME = "SEOFields";


        /// <summary>
        /// SEOTitle.
        /// </summary>
        public string SEOTitle { get; set; }


        /// <summary>
        /// SEODescription.
        /// </summary>
        public string SEODescription { get; set; }
    }
}