//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;
using CMS.Websites;
using XperienceAdapter.Models.ReusableContentTypes.DancingGoat.Image;
using XperienceAdapter.Models.ReusableFieldSchemas.SEOFields.SEOFields;

namespace XperienceAdapter.Models.PageContentTypes.DancingGoat.Content
{
    /// <summary>
    /// Represents a page of type <see cref="Content"/>.
    /// </summary>
    [RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
    public partial class Content : IWebPageFieldsSource, ISEOFields
    {
        /// <summary>
        /// Code name of the content type.
        /// </summary>
        public const string CONTENT_TYPE_NAME = "DancingGoat.Content";


        /// <summary>
        /// Represents system properties for a web page item.
        /// </summary>
        [SystemField]
        public WebPageFields SystemFields { get; set; }


        /// <summary>
        /// Title.
        /// </summary>
        public string Title { get; set; }


        /// <summary>
        /// Description.
        /// </summary>
        public string Description { get; set; }


        /// <summary>
        /// Categories.
        /// </summary>
        public IEnumerable<TagReference> Categories { get; set; }


        /// <summary>
        /// test.
        /// </summary>
        public int test { get; set; }


        /// <summary>
        /// ImageThumbnail.
        /// </summary>
        public IEnumerable<Image> ImageThumbnail { get; set; }


        /// <summary>
        /// BackgroundColor.
        /// </summary>
        public string BackgroundColor { get; set; }


        /// <summary>
        /// teststring.
        /// </summary>
        public string teststring { get; set; }


        /// <summary>
        /// SEOTitle.
        /// </summary>
        public string SEOTitle { get; set; }


        /// <summary>
        /// SEODescription.
        /// </summary>
        public string SEODescription { get; set; }
    }
}