//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;
using CMS.Websites;
using XperienceAdapter.Models.ReusableFieldSchemas.SEOFields.SEOFields;

namespace XperienceAdapter.Models.PageContentTypes.DancingGoat.Home
{
    /// <summary>
    /// Represents a page of type <see cref="Home"/>.
    /// </summary>
    [RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
    public partial class Home : IWebPageFieldsSource, ISEOFields
    {
        /// <summary>
        /// Code name of the content type.
        /// </summary>
        public const string CONTENT_TYPE_NAME = "DancingGoat.Home";


        /// <summary>
        /// Represents system properties for a web page item.
        /// </summary>
        [SystemField]
        public WebPageFields SystemFields { get; set; }


        /// <summary>
        /// Title.
        /// </summary>
        public string Title { get; set; }


        /// <summary>
        /// SEOTItle.
        /// </summary>
        public string SEOTitle { get; set; }


        /// <summary>
        /// SEODescription.
        /// </summary>
        public string SEODescription { get; set; }
    }
}